People:
  actAs:
    Timestampable:        ~
  columns:
    lastname:             varchar(255)
    firstname:            varchar(255)
    company_name:         varchar(255)
    phone:                varchar(15)
    email:                varchar(255)
    picture_url:          varchar(255)